### ISSUE TITLE
When element binding 'v-click-outside' is unbind, but event does not removed.

### ISSUE THREAD

**Issue by yu1222** [ndelvalle/v-click-outside#62] opened 2019-04-19 02:09 UTC
When element binding 'v-click-outside' is unbind, but event does not removed.
```html
<div v-if="show" v-click-outside="handler" />
// (show toggle true/false -> add event handler more and more)
```

![1555639264](https://user-images.githubusercontent.com/6902359/56401293-1abfc200-6293-11e9-8968-be475bfbc85a.png)

vue version 2.6.2
v-click-outside version 2.1.1
(The version of 2.0.1 worked normally.)

check this please..
thank you.

**Comment by seanmcoleman** [comment] 2019-04-30 21:28
I am also experiencing this behavior in a new app.

**Comment by trongthanh** [comment] 2019-05-02 10:04
I think I've found the cause of the issue.

I think it is because of [these lines](https://github.com/ndelvalle/v-click-outside/blob/master/lib/v-click-outside.js#L74):

```
setTimeout(document.addEventListener, 0, event, handler)
```

It can be fixed by just add the event listener directly, like so:

```
document.addEventListener(event, handler);
```
Reason: when you place `document.addEventListener` as callback for `setTimeout`, it will be executed without context object, ie. anonymously, and since this code is not in strict mode, `this` will be bound to `window`. So, you are addingEventListener to `window` and removeEventListener from `document`, which of course, did not really removing the handlers.

I can send a pull request to fix this, but need to clarify why are we adding event listeners asynchronously with `setTimeout` first?

**Comment by ndelvalle** [comment] 2019-05-02 14:33
@trongthanh thanks for the contribution, more info about why we used setTimeout can be found in issue #41 (I'm not even sure this still a problem in current vue versions)
Anyways, we can bind the context using `.bind`, or use it in a more conventional way, like:

` setTimeout(() => document.addEventListener(event, handler), 0)`

What do you think?

**Comment by trongthanh** [comment] 2019-05-02 16:02
Regarding issue #41, from my experience with normal DOM events, I often call event.stopPropagation() in the user's click event handler, so that the event is not bubbled up the document during which a click handler is registered at it. But it's only applicable for events that library code can control and besides, I'm not sure if its applicable for Vue's directive binding.

So, I can't think of any better solution than setTimeout for now. And your suggestion to call `document.addEventListener` like above should be fine.

**Comment by trongthanh** [comment] 2019-05-06 05:00
@ndelvalle I had a quick test and this issue seem to be gone in 2.1.2-0. But there are other changes in PR #69. So it's your call to verify those changes and make an official publish.

**Comment by Suruat** [comment] 2019-05-06 14:32
@ndelvalle When we can expect to see those changes on NPM ?

**Comment by ndelvalle** [comment] 2019-05-07 07:08
v-click-outside 2.1.2 published 🎉

**Closed** 2019-05-16 13:40 UTC
